import { createContext, useContext, useEffect, useState, ReactNode, useCallback } from "react";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/useAuth";

export type AppRole = "admin" | "super_admin" | "super_user" | "compliance_team" | "data_entry_team" | "user";
export interface RBACPermissions {
  canViewProfiles: boolean; canEditProfiles: boolean; canEditProfileIdentity: boolean; canEditProfileEmployment: boolean;
  canEditLoanApplications: boolean; canExportData: boolean; canViewAuditLogs: boolean; canViewLoanApplications: boolean;
  canChangeSystemSettings: boolean; canManageUsers: boolean; canAssignRoles: boolean; canDeactivateUsers: boolean;
  canDeleteRecords: boolean; canApproveChanges: boolean; canUploadDocuments: boolean;
  canManageLenderProducts: boolean; canManageCommissions: boolean; canViewFinancials: boolean; canManagePayouts: boolean;
  canManageAutomations: boolean; canManageRoles: boolean; canExportCustomerData: boolean; canPerformCreditChecks: boolean;
  canViewPayroll: boolean;
}
export const ROLE_PERMISSIONS: Record<AppRole, RBACPermissions> = {
  super_admin: { canViewProfiles:true,canEditProfiles:true,canEditProfileIdentity:true,canEditProfileEmployment:true,canEditLoanApplications:true,canExportData:true,canViewAuditLogs:true,canViewLoanApplications:true,canChangeSystemSettings:true,canManageUsers:true,canAssignRoles:true,canDeactivateUsers:true,canDeleteRecords:true,canApproveChanges:true,canUploadDocuments:true,canManageLenderProducts:true,canManageCommissions:true,canViewFinancials:true,canManagePayouts:true,canManageAutomations:true,canManageRoles:true,canExportCustomerData:true,canPerformCreditChecks:true,canViewPayroll:true },
  admin: { canViewProfiles:true,canEditProfiles:true,canEditProfileIdentity:true,canEditProfileEmployment:true,canEditLoanApplications:true,canExportData:true,canViewAuditLogs:true,canViewLoanApplications:true,canChangeSystemSettings:false,canManageUsers:true,canAssignRoles:true,canDeactivateUsers:true,canDeleteRecords:false,canApproveChanges:true,canUploadDocuments:true,canManageLenderProducts:true,canManageCommissions:true,canViewFinancials:true,canManagePayouts:true,canManageAutomations:true,canManageRoles:true,canExportCustomerData:true,canPerformCreditChecks:true,canViewPayroll:true },
  super_user: { canViewProfiles:true,canEditProfiles:true,canEditProfileIdentity:true,canEditProfileEmployment:true,canEditLoanApplications:true,canExportData:true,canViewAuditLogs:true,canViewLoanApplications:true,canChangeSystemSettings:false,canManageUsers:false,canAssignRoles:false,canDeactivateUsers:false,canDeleteRecords:false,canApproveChanges:false,canUploadDocuments:true,canManageLenderProducts:false,canManageCommissions:false,canViewFinancials:true,canManagePayouts:false,canManageAutomations:false,canManageRoles:false,canExportCustomerData:true,canPerformCreditChecks:false,canViewPayroll:false },
  compliance_team: { canViewProfiles:true,canEditProfiles:false,canEditProfileIdentity:false,canEditProfileEmployment:false,canEditLoanApplications:false,canExportData:false,canViewAuditLogs:true,canViewLoanApplications:true,canChangeSystemSettings:false,canManageUsers:false,canAssignRoles:false,canDeactivateUsers:false,canDeleteRecords:false,canApproveChanges:false,canUploadDocuments:false,canManageLenderProducts:false,canManageCommissions:false,canViewFinancials:false,canManagePayouts:false,canManageAutomations:false,canManageRoles:false,canExportCustomerData:false,canPerformCreditChecks:false,canViewPayroll:true },
  data_entry_team: { canViewProfiles:true,canEditProfiles:true,canEditProfileIdentity:true,canEditProfileEmployment:false,canEditLoanApplications:false,canExportData:false,canViewAuditLogs:false,canViewLoanApplications:false,canChangeSystemSettings:false,canManageUsers:false,canAssignRoles:false,canDeactivateUsers:false,canDeleteRecords:false,canApproveChanges:false,canUploadDocuments:true,canManageLenderProducts:false,canManageCommissions:false,canViewFinancials:false,canManagePayouts:false,canManageAutomations:false,canManageRoles:false,canExportCustomerData:false,canPerformCreditChecks:false,canViewPayroll:false },
  user: { canViewProfiles:true,canEditProfiles:false,canEditProfileIdentity:false,canEditProfileEmployment:false,canEditLoanApplications:false,canExportData:false,canViewAuditLogs:false,canViewLoanApplications:false,canChangeSystemSettings:false,canManageUsers:false,canAssignRoles:false,canDeactivateUsers:false,canDeleteRecords:false,canApproveChanges:false,canUploadDocuments:true,canManageLenderProducts:false,canManageCommissions:false,canViewFinancials:false,canManagePayouts:false,canManageAutomations:false,canManageRoles:false,canExportCustomerData:false,canPerformCreditChecks:false,canViewPayroll:false },
};
export const DATA_ENTRY_EDITABLE_FIELDS = ["full_name", "nrc_number"];
export const SUPER_USER_PROFILE_FIELDS = ["full_name", "nrc_number", "phone", "email", "employer", "employee_number", "salary"];
interface RBACContextType { roles: AppRole[]; permissions: RBACPermissions; loading: boolean; highestRole: AppRole | null; hasRole: (role: AppRole) => boolean; logAction: (action: string, recordId?: string, tableName?: string, oldValue?: unknown, newValue?: unknown) => Promise<void>; }
const defaultPermissions = Object.fromEntries(Object.keys(ROLE_PERMISSIONS.user).map((key) => [key, false])) as RBACPermissions;
const RBACContext = createContext<RBACContextType>({ roles: [], permissions: defaultPermissions, loading: true, highestRole: null, hasRole: () => false, logAction: async () => {} });
const ROLE_PRIORITY: AppRole[] = ["super_admin", "admin", "super_user", "compliance_team", "data_entry_team", "user"];
function mergePermissions(roles: AppRole[]): RBACPermissions { const merged = { ...defaultPermissions }; for (const role of roles) { const perms = ROLE_PERMISSIONS[role]; if (!perms) continue; for (const key of Object.keys(merged) as (keyof RBACPermissions)[]) if (perms[key]) merged[key] = true; } return merged; }
export const RBACProvider = ({ children }: { children: ReactNode }) => { const { user } = useAuth(); const [roles, setRoles] = useState<AppRole[]>([]); const [loading, setLoading] = useState(true); useEffect(() => { if (!user) { setRoles([]); setLoading(false); return; } const fetchRoles = async () => { const { data } = await supabase.from("user_roles").select("role").eq("user_id", user.id); setRoles((data?.map((r) => r.role) ?? []) as AppRole[]); setLoading(false); }; fetchRoles(); }, [user]); const permissions = mergePermissions(roles); const highestRole = ROLE_PRIORITY.find((r) => roles.includes(r)) ?? null; const hasRole = useCallback((role: AppRole) => roles.includes(role), [roles]); const logAction = useCallback(async (action: string, recordId?: string, tableName?: string, oldValue?: unknown, newValue?: unknown) => { if (!user) return; await supabase.rpc("log_audit", { _user_id:user.id,_role:highestRole ?? "unknown",_action:action,_record_id:recordId ?? null,_table_name:tableName ?? null,_old_value:oldValue ? JSON.stringify(oldValue) : null,_new_value:newValue ? JSON.stringify(newValue) : null }); }, [user, highestRole]); return <RBACContext.Provider value={{ roles, permissions, loading, highestRole, hasRole, logAction }}>{children}</RBACContext.Provider>; };
export const useRBAC = () => useContext(RBACContext);
export const ROLE_LABELS: Record<string, string> = { super_admin:"Super Admin", admin:"Admin", super_user:"Super User", compliance_team:"Compliance Team", data_entry_team:"Data Entry Team", user:"User" };
export const ROLE_DESCRIPTIONS: Record<string, string> = { super_admin:"Full platform access including system settings and configuration", admin:"Full admin access except system settings", super_user:"Can view and edit operational data, export permitted reports, and view audit logs. Cannot change system settings or manage privileged administration.", compliance_team:"Read-only access to profiles, applications, and audit logs for compliance monitoring.", data_entry_team:"Can edit basic identity fields and upload ID documents only." };