// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-my-kyc-status.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.97.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-my-kyc-status.ts
var get_my_kyc_status_default = defineTool({
  name: "get_my_kyc_status",
  title: "Get my KYC status",
  description: "Return the signed-in user's KYC verification status, employer details and consent state on Riverbanc.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("profiles").select(
      "full_name, kyc_status, account_status, employer, nrc_verified, phone_verified, consent_accepted, consent_signed_at, consent_marketing, consent_data_sharing_lenders, consent_crb_check, consent_analytics"
    ).eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    if (!data) {
      return { content: [{ type: "text", text: "No profile found for this account yet." }] };
    }
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/list-my-loan-applications.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";
var list_my_loan_applications_default = defineTool2({
  name: "list_my_loan_applications",
  title: "List my loan applications",
  description: "List the signed-in user's Riverbanc loan applications with status, requested amount, selected lender and decision.",
  inputSchema: {
    limit: z.number().int().optional().describe("Maximum applications to return (default 10, max 50)."),
    status: z.string().optional().describe("Optional status filter, e.g. PENDING, APPROVED, DECLINED.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit, status }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const take = Math.min(Math.max(limit ?? 10, 1), 50);
    const supabase = supabaseForUser(ctx);
    let query = supabase.from("loan_applications").select(
      "id, status, decision, decision_reason, requested_amount, selected_lender, selected_interest_rate, selected_repayment_months, estimated_monthly_repayment, created_at, updated_at"
    ).eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(take);
    if (status) query = query.eq("status", status);
    const { data, error } = await query;
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [
        {
          type: "text",
          text: data?.length ? JSON.stringify(data, null, 2) : "No loan applications found."
        }
      ],
      structuredContent: { applications: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/list-lender-products.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var list_lender_products_default = defineTool3({
  name: "list_lender_products",
  title: "List lender products",
  description: "List active Riverbanc lender loan products with interest rates, amount ranges and terms, for comparison.",
  inputSchema: {
    amount: z2.number().optional().describe("Optional loan amount in ZMW to filter products that support it.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ amount }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("bank_products").select("id, bank_name, interest_rate, min_amount, max_amount, max_term_months, processing_days").eq("active", true).order("interest_rate", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const products = (data ?? []).filter((p) => {
      if (amount === void 0) return true;
      const min = p.min_amount ?? 0;
      const max = p.max_amount ?? Number.MAX_SAFE_INTEGER;
      return amount >= min && amount <= max;
    });
    return {
      content: [
        {
          type: "text",
          text: products.length ? JSON.stringify(products, null, 2) : "No matching lender products."
        }
      ],
      structuredContent: { products }
    };
  }
});

// src/lib/mcp/tools/check-affordability.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var check_affordability_default = defineTool4({
  name: "check_affordability",
  title: "Check loan affordability",
  description: "Check a loan against the Zambian one-third-of-net-salary affordability rule and return the estimated monthly repayment.",
  inputSchema: {
    net_salary: z3.number().describe("Monthly net salary in ZMW."),
    amount: z3.number().describe("Requested loan amount in ZMW."),
    term_months: z3.number().int().describe("Repayment term in months."),
    annual_interest_rate: z3.number().optional().describe("Annual interest rate as a percentage, e.g. 24 for 24%. Defaults to 24.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: ({ net_salary, amount, term_months, annual_interest_rate }) => {
    if (net_salary <= 0 || amount <= 0 || term_months <= 0) {
      return {
        content: [{ type: "text", text: "net_salary, amount and term_months must all be greater than zero." }],
        isError: true
      };
    }
    const annualRate = annual_interest_rate ?? 24;
    const monthlyRate = annualRate / 100 / 12;
    const monthlyRepayment = monthlyRate === 0 ? amount / term_months : amount * monthlyRate / (1 - Math.pow(1 + monthlyRate, -term_months));
    const maxAffordable = net_salary / 3;
    const affordable = monthlyRepayment <= maxAffordable;
    const round = (v) => Math.round(v * 100) / 100;
    const result = {
      monthly_repayment_zmw: round(monthlyRepayment),
      max_affordable_monthly_zmw: round(maxAffordable),
      affordable,
      rule: "Monthly repayment must not exceed one third of net salary.",
      annual_interest_rate: annualRate,
      term_months
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "amjbvphgwhtfcbbmmpzz";
var mcp_default = defineMcp({
  name: "riverbanc-technology",
  title: "RIVERBANC TECHNOLOGY",
  version: "0.1.0",
  instructions: "Tools for Riverbanc, a lending platform for Zambian civil servants. Use `get_my_kyc_status` for the signed-in user's verification and consent state, `list_my_loan_applications` for their applications, `list_lender_products` to compare active lender offers, and `check_affordability` to apply the one-third-of-net-salary rule.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_my_kyc_status_default, list_my_loan_applications_default, list_lender_products_default, check_affordability_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
