-- Historical migration marker for remote version 20260811064451.
-- Effective storage policy is represented by the later authoritative KYC
-- storage migrations; retain this exact timestamp for migration replay.
