import { useEffect, useState } from "react";
import { Badge } from "@/components/ui/badge";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Progress } from "@/components/ui/progress";
import { Activity, ArrowUpRight, Banknote, BriefcaseBusiness, Clock3, FileCheck, RefreshCw, ShieldAlert, Users } from "lucide-react";
import { getDashboardMetrics, type DashboardMetrics } from "./dashboardMetrics";

const emptyMetrics: DashboardMetrics = { activeBorrowers: 0, pendingApplications: 0, monthlySubscriptionValue: 0, riskAlerts: 0, priorityQueue: [], recentActivity: [], pipeline: [], lenderHealth: [] };

const Dashboard = () => {
  const [metrics, setMetrics] = useState(emptyMetrics);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);

  const loadMetrics = async () => {
    setLoading(true); setError(null);
    try { setMetrics(await getDashboardMetrics()); }
    catch (err) { setError(err instanceof Error ? err.message : "Unable to load Command Center data"); }
    finally { setLoading(false); }
  };

  useEffect(() => { void loadMetrics(); const interval = window.setInterval(() => void loadMetrics(), 60_000); return () => window.clearInterval(interval); }, []);

  const stats = [
    { label: "Active borrowers", value: metrics.activeBorrowers.toLocaleString(), delta: "Live account count", icon: Users, tone: "from-sky-500/20 to-sky-400/5" },
    { label: "Pending applications", value: metrics.pendingApplications.toLocaleString(), delta: "Awaiting operational review", icon: FileCheck, tone: "from-amber-400/20 to-amber-300/5" },
    { label: "Monthly subscription value", value: `K ${metrics.monthlySubscriptionValue.toLocaleString()}`, delta: "K60 per active member per month", icon: Banknote, tone: "from-emerald-400/20 to-emerald-300/5" },
    { label: "Risk alerts", value: metrics.riskAlerts.toLocaleString(), delta: "Unresolved risk flags", icon: ShieldAlert, tone: "from-rose-400/20 to-rose-300/5" },
  ];

  return <div className="mx-auto max-w-7xl space-y-6">
    <div className="overflow-hidden rounded-[28px] border border-border/30 bg-gradient-to-br from-slate-950 via-slate-900 to-primary/20 shadow-2xl p-6 md:p-8 lg:p-10"><div className="flex flex-col gap-8"><div className="flex flex-col gap-8 xl:flex-row xl:items-end xl:justify-between"><div className="max-w-3xl space-y-4"><Badge className="border-white/15 bg-white/10 px-3 py-1 text-xs font-medium text-white/80">Daily operations overview</Badge><h1 className="max-w-2xl text-4xl font-display font-bold leading-tight text-white md:text-5xl">Admin command center for <span className="text-gradient">live lending activity</span></h1><p className="max-w-2xl text-base text-white/70 md:text-lg">Track application flow, subscription health, and compliance pressure using live platform data.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:w-[420px]"><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.24em] text-white/45">Data</p><p className="mt-3 text-3xl font-display font-bold text-white">{loading ? "—" : "LIVE"}</p><p className="text-sm text-white/60">refreshes every minute</p></div><div className="rounded-2xl border border-white/10 bg-white/5 p-4"><p className="text-xs uppercase tracking-[0.24em] text-white/45">Attention</p><p className="mt-3 text-3xl font-display font-bold text-white">{loading ? "—" : metrics.priorityQueue.length}</p><p className="text-sm text-white/60">priority items</p></div></div></div>{error && <div className="rounded-2xl border border-rose-400/30 bg-rose-500/10 p-4 text-sm text-white">{error}</div>}<div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-4">{stats.map((stat) => <div key={stat.label} className={`rounded-2xl border border-white/10 bg-gradient-to-br ${stat.tone} p-5`}><div className="flex items-start justify-between gap-3"><div><p className="text-sm text-white/60">{stat.label}</p><p className="text-3xl font-display font-bold text-white">{loading ? "—" : stat.value}</p></div><stat.icon className="h-5 w-5 text-white/70" /></div><p className="mt-4 flex items-center gap-2 text-sm text-white/70"><ArrowUpRight className="h-4 w-4" />{stat.delta}</p></div>)}</div></div></div>
    <div className="grid gap-6 xl:grid-cols-[1.4fr_1fr]"><Card><CardHeader><div className="flex items-center justify-between gap-4"><div><CardTitle>Priority Queue</CardTitle><p className="mt-1 text-sm text-muted-foreground">Live work items requiring operational attention.</p></div><Badge variant="secondary">{metrics.priorityQueue.length} priority items</Badge></div></CardHeader><CardContent className="space-y-3">{loading ? <p className="text-sm text-muted-foreground">Loading operational queue…</p> : metrics.priorityQueue.length === 0 ? <p className="text-sm text-muted-foreground">No priority items require attention.</p> : metrics.priorityQueue.map((item) => <div key={item.title} className="flex flex-col gap-3 rounded-2xl border p-4 md:flex-row md:items-center md:justify-between"><div><p className="text-sm font-semibold">{item.title}</p><p className="text-sm text-muted-foreground">{item.owner}</p></div><div className="flex items-center gap-3"><Badge className={`border ${item.badgeClass}`}>{item.badge}</Badge><span className="text-sm text-muted-foreground">{item.eta}</span></div></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Live Activity</CardTitle><p className="text-sm text-muted-foreground">Most recent audited platform events.</p></CardHeader><CardContent className="space-y-4">{loading ? <p className="text-sm text-muted-foreground">Loading activity…</p> : metrics.recentActivity.length === 0 ? <p className="text-sm text-muted-foreground">No recent activity recorded.</p> : metrics.recentActivity.map((item) => <div key={`${item.action}-${item.time}`} className="flex items-start gap-3"><span className="mt-1.5 h-2.5 w-2.5 rounded-full bg-primary" /><div className="flex-1"><p className="text-sm font-medium">{item.action}</p><p className="text-sm text-muted-foreground">{item.user}</p></div><span className="flex items-center gap-1 text-xs text-muted-foreground"><Clock3 className="h-3.5 w-3.5" />{item.time}</span></div>)}</CardContent></Card></div>
    <div className="grid gap-6 lg:grid-cols-2"><Card><CardHeader><CardTitle>Application Pipeline</CardTitle><p className="text-sm text-muted-foreground">Live distribution across the application workflow.</p></CardHeader><CardContent className="space-y-5">{loading ? <p className="text-sm text-muted-foreground">Loading pipeline…</p> : metrics.pipeline.map((stage) => <div key={stage.stage} className="space-y-2"><div className="flex items-center justify-between"><span className="text-sm font-medium">{stage.stage}</span><span className="text-sm text-muted-foreground">{stage.count} · {stage.share}%</span></div><Progress value={stage.share} /></div>)}</CardContent></Card><Card><CardHeader><CardTitle>Lender Health</CardTitle><p className="text-sm text-muted-foreground">Live product availability across partner lenders.</p></CardHeader><CardContent className="space-y-5">{loading ? <p className="text-sm text-muted-foreground">Loading lender health…</p> : metrics.lenderHealth.length === 0 ? <p className="text-sm text-muted-foreground">No lender products are currently recorded.</p> : metrics.lenderHealth.map((lender) => <div key={lender.name} className="space-y-2"><div className="flex items-center justify-between"><div className="flex items-center gap-2"><BriefcaseBusiness className="h-4 w-4 text-muted-foreground" /><div><p className="text-sm font-semibold">{lender.name}</p><p className="text-xs text-muted-foreground">{lender.subtitle}</p></div></div><span className="text-sm font-medium">{lender.fill}%</span></div><Progress value={lender.fill} /></div>)}<div className="rounded-2xl border bg-muted/40 p-4"><div className="flex items-center gap-3"><Activity className="h-5 w-5 text-primary" /><div><p className="text-sm font-semibold">Command Center data is live</p><p className="text-sm text-muted-foreground">Use specialist Admin pages for detailed investigation and action.</p></div></div></div></CardContent></Card></div>
    <div className="flex justify-end"><button type="button" onClick={() => void loadMetrics()} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm text-muted-foreground hover:bg-muted"><RefreshCw className="h-4 w-4" />Refresh</button></div>
  </div>;
};

export default Dashboard;